// Mock data for development (when Sanity CMS is not connected)
export const mockServices = [
  {
    _id: '1',
    titleFi: 'Käsinpesu',
    titleEn: 'Hand Wash',
    descriptionFi: 'Huolellinen käsinpesu, joka palauttaa autosi pinnan raikkauden.',
    descriptionEn: 'Careful hand wash that restores your car\'s surface freshness.',
    price: 25,
    duration: 30,
    capacity: 2,
    image: '/images/service-kasinpesu.svg',
    isActive: true,
    category: 'wash' as const,
  },
  {
    _id: '2',
    titleFi: 'Käsinpesu + Pikavaha',
    titleEn: 'Hand Wash + Quick Wax',
    descriptionFi: 'Kevyt vaha antaa upean kiillon ja suojaa autoasi heti pesun jälkeen.',
    descriptionEn: 'Light wax gives great shine and protects your car right after washing.',
    price: 30,
    duration: 40,
    capacity: 2,
    image: '/images/service-pikavaha.svg',
    isActive: true,
    category: 'wash' as const,
  },
  {
    _id: '3',
    titleFi: 'Käsinpesu + Sisäpuhdistus',
    titleEn: 'Hand Wash + Interior Cleaning',
    descriptionFi: 'Kokonaisvaltainen puhdistus: matot, imurointi, ikkunat ja pölyjen poisto.',
    descriptionEn: 'Comprehensive cleaning: carpets, vacuuming, windows and dust removal.',
    price: 55,
    duration: 60,
    capacity: 2,
    image: '/images/service-sisapuhdistus.svg',
    isActive: true,
    category: 'wash' as const,
  },
  {
    _id: '4',
    titleFi: 'Käsinpesu + Normaalivaha',
    titleEn: 'Hand Wash + Normal Wax',
    descriptionFi: 'Vahapinnoite, joka säilyttää kiillon ja suojan jopa 2–3 kuukauden ajan.',
    descriptionEn: 'Wax coating that maintains shine and protection for up to 2-3 months.',
    price: 70,
    duration: 50,
    capacity: 2,
    image: '/images/service-normaalivaha.svg',
    isActive: true,
    category: 'wash' as const,
  },
  {
    _id: '5',
    titleFi: 'Käsinpesu + Kovavaha',
    titleEn: 'Hand Wash + Hard Wax',
    descriptionFi: 'Pitkäkestoinen 6 kk suoja ja upea kiilto kovavahauksella.',
    descriptionEn: 'Long-lasting 6 month protection and beautiful shine with hard wax.',
    price: 110,
    duration: 70,
    capacity: 2,
    image: '/images/service-kovavaha.svg',
    isActive: true,
    category: 'wash' as const,
  },
  {
    _id: '6',
    titleFi: 'Maalipinnan Kiillotus',
    titleEn: 'Paint Polishing',
    descriptionFi: '3 step kiillotus sekä käsinvahaus. Henkilöauto 350€, Maasturi 400€, Pakettiauto 450€.',
    descriptionEn: '3-step polishing and hand waxing. Car 350€, SUV 400€, Van 450€.',
    price: 350,
    duration: 180,
    capacity: 1,
    image: '/images/service-kiillotus.svg',
    isActive: true,
    category: 'premium' as const,
  },
  {
    _id: '7',
    titleFi: 'Renkaiden Vaihto',
    titleEn: 'Tire Change',
    descriptionFi: 'Turvallisuutta ja varmuutta ajoon – renkaiden allevaihto ja paineiden tarkistus.',
    descriptionEn: 'Safety and reliability for driving – tire change and pressure check.',
    price: 20,
    duration: 25,
    capacity: 2,
    image: '/images/service-renkaiden-vaihto.svg',
    isActive: true,
    category: 'tire' as const,
  },
  {
    _id: '8',
    titleFi: 'Renkaiden Pesu',
    titleEn: 'Tire Wash',
    descriptionFi: 'Puhtaat renkaat ja vanteet sekä sisältä että ulkoa.',
    descriptionEn: 'Clean tires and rims both inside and outside.',
    price: 10,
    duration: 15,
    capacity: 4,
    image: '/images/service-renkaiden-pesu.svg',
    isActive: true,
    category: 'tire' as const,
  },
  {
    _id: '9',
    titleFi: 'Rengashotelli',
    titleEn: 'Tire Hotel',
    descriptionFi: 'Helppoutta ja tilansäästöä – kausisäilytys keväästä syksyyn tai syksystä kevääseen.',
    descriptionEn: 'Convenience and space saving – seasonal storage from spring to autumn or autumn to spring.',
    price: 69,
    duration: 30,
    capacity: 3,
    image: '/images/service-rengashotelli.svg',
    isActive: true,
    category: 'tire' as const,
  },
  {
    _id: '10',
    titleFi: 'Moottorin Pesu',
    titleEn: 'Engine Wash',
    descriptionFi: 'Puhdas moottoritila – aina asiakkaan omalla vastuulla.',
    descriptionEn: 'Clean engine bay – always at customer\'s own responsibility.',
    price: 20,
    duration: 30,
    capacity: 2,
    image: '/images/service-moottori.svg',
    isActive: true,
    category: 'additional' as const,
  },
  {
    _id: '11',
    titleFi: 'Hajunpoisto Otsonoinnilla',
    titleEn: 'Odor Removal with Ozone',
    descriptionFi: 'Raikas sisäilma – tehokas otsonointi poistaa epämiellyttävät hajut.',
    descriptionEn: 'Fresh interior air – effective ozone treatment removes unpleasant odors.',
    price: 50,
    duration: 60,
    capacity: 1,
    image: '/images/service-hajunpoisto.svg',
    isActive: true,
    category: 'additional' as const,
  },
  {
    _id: '12',
    titleFi: 'Penkkien Pesu',
    titleEn: 'Seat Cleaning',
    descriptionFi: 'Syväpuhdistetut penkit – kemiallinen märkäpesu palauttaa raikkauden.',
    descriptionEn: 'Deep-cleaned seats – chemical wet cleaning restores freshness.',
    price: 100,
    duration: 90,
    capacity: 1,
    image: '/images/service-penkit.svg',
    isActive: true,
    category: 'additional' as const,
  },
];

export const mockTestimonials = [
  {
    _id: '1',
    name: 'Matti M.',
    contentFi: 'Loistava palvelu! Auto näyttää uudelta.',
    contentEn: 'Excellent service! Car looks like new.',
    rating: 5,
    approved: true,
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    _id: '2',
    name: 'Laura K.',
    contentFi: 'Ammattitaitoista työtä, suosittelen lämpimästi!',
    contentEn: 'Professional work, highly recommend!',
    rating: 5,
    approved: true,
    createdAt: '2025-01-10T00:00:00Z',
  },
  {
    _id: '3',
    name: 'Jari P.',
    contentFi: 'Nopea ja huolellinen pesu. Hinta-laatusuhde kohdallaan.',
    contentEn: 'Fast and careful wash. Good value for money.',
    rating: 5,
    approved: true,
    createdAt: '2025-01-05T00:00:00Z',
  },
];